---

# FROM package_uninstall
- name: Populate service facts
  ansible.builtin.service_facts:

- name: ensure infra-agent service is not present
  assert:
    that: "ansible_facts.services['{{ service_name }}'] is not defined"

...
