---

- name: Set displayName as hostname
  win_hostname:
    name: "{{ hostname }}"
  register: res

- name: Reboot
  win_reboot:
    reboot_timeout: 1200 # default 600s is occasionally too tight for slower-booting instances
  when: res.reboot_required

- name: Wait until host is up-and-running again
  win_ping:
  register: lsresult
  until: "lsresult is not failed"
  retries: 10
  delay: 10

...