---

- name: create newrelic-infra directory structure
  win_file:
    path: C:\Program Files\New Relic\newrelic-infra
    state: directory

- name: install infra-agent configuration file
  template:
    src: "{{ config_template }}"
    dest: C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml
  no_log: true

...
