---

- name: setup NR repository
  include_role:
    name: nr_repo_setup

- name: register brew path
  ansible.builtin.set_fact:
    brew_path: /opt/homebrew
    when: ansible_architecture == "arm64"

- name: register brew path
  ansible.builtin.set_fact:
    brew_path: /usr/local
  when: ansible_architecture == "x86_64"

# Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.
- name: brew update
  command: "{{ brew_path }}/bin/brew update"
  become: false

- name: Stop launchctl service
  command: "{{ brew_path }}/bin/brew services stop newrelic-infra-agent"
  ignore_errors: yes

- name: Agent uninstall
  become: false
  command: "{{ brew_path }}/bin/brew uninstall --force newrelic-infra-agent"
  ignore_errors: yes

- name: cleanup | Remove files
  command: "rm -rf {{ brew_path }}/Cellar/newrelic-infra-agent"

  # Avoid errors with commit hash on tag recreation
- name: delete brew cache (avoid tag recreation commit error)
  file:
    path: "/Users/{{ ansible_user }}/Library/Caches/Homebrew"
    state: absent

- name: Install agent
  become: false
  command: "{{ brew_path }}/bin/brew reinstall --force --formula --build-from-source /Users/{{ ansible_user }}/newrelic-infra-agent.rb"

- name: Start launchctl service
  shell: "HOMEBREW_NO_INSTALL_FROM_API=1 {{ brew_path }}/bin/brew services restart newrelic-infra-agent"

...
