---

- name: setup NR repository
  ansible.builtin.include_role:
    name: nr_repo_setup

- name: Install package
  ansible.builtin.include_role:
    name: package_install
  vars:
    package: "{{ 'newrelic-infra-fips' if fips_enabled else 'newrelic-infra' }}"

- name: Assert service status
  ansible.builtin.include_role:
    name: assert_service_status
  vars:
    services_enabled:
      - "newrelic-infra.service"
    services_running:
      - "newrelic-infra.service"

- name: assert embedded integrations architecture
  include_tasks: embedded-integrations-architecture.yaml
...
