---

- name: yum remove package
  yum:
    name: "{{ package }}"
    state: absent
  when: ansible_distribution_major_version != '5' and not ansible_python_interpreter is regex("python3$")

- name: dnf remove package
  dnf:
    name: "{{ package }}"
    state: absent
  when: ansible_distribution_major_version != '5' and ansible_python_interpreter is regex("python3$")

- name: yum remove package (rhel5)
  shell: "yum -y remove {{ package }}"
  when: ansible_distribution_major_version == '5'


...
