- name: set the release facts for amd64
  set_fact:
    file_name: "{{ collector_latest.name }}"
    download_url: "{{ collector_latest.browser_download_url }}"
    collector: "{{ collector_latest }}"
  vars:
    collector_latest: "{{ github_packages.json|to_json|from_json|json_query('assets[?ends_with(name,`amd64.rpm`)]') | selectattr('name', 'match', distribution + '_') | first  }}"
  when: ansible_architecture == "x86_64"

- name: set the release facts for arm64
  set_fact:
    file_name: "{{ collector_latest.name }}"
    download_url: "{{ collector_latest.browser_download_url }}"
    collector: "{{ collector_latest }}"
  vars:
    collector_latest: "{{ github_packages.json|to_json|from_json|json_query('assets[?ends_with(name,`arm64.rpm`)]') | selectattr('name', 'match', distribution + '_') | first  }}"
  when: ansible_architecture == "aarch64"

- name: download the latest release
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_path }}"

- name: Install OpenTelemetry Collector
  dnf:
    name: "{{ download_path + file_name }}"
    disable_gpg_check: true
  notify:
    - restart collector
