---

# Currently package from production is installed because stg does not have https and nr-cli verifies this
# Until this is fixed we need to clean metadata to avoid error: "Not using downloaded repomd.xml because it is older than what we have"
- name: clean metadata
  command: yum clean metadata
  when: ansible_pkg_mgr == 'yum'

- name: Download newrelic-cli installer [satya 18]
  get_url:
    url: https://raw.githubusercontent.com/newrelic/newrelic-cli/master/scripts/install.sh
    dest: /tmp/newrelic-cli-install.sh
    mode: '0111'

- name: Install newrelic-cli [satya 18]
  shell: yes | /tmp/newrelic-cli-install.sh

- name: Install agent via newrelic-cli [satya 18]
  no_log: true
  shell: NEW_RELIC_DOWNLOAD_URL="https://nr-downloads-ohai-staging.s3.amazonaws.com/" NEW_RELIC_REGION="{{ region }}" NEW_RELIC_API_KEY={{ nr_api_key }} NEW_RELIC_ACCOUNT_ID={{ nr_account_id }} /usr/local/bin/newrelic install -n {{ recipe }} --debug -y
