---
- name: Create folder for docker-compose
  file:
    path: "{{ dockerfile_directory }}"
    state: directory
    mode: '0755'

- name: Copy Dockerfile
  template:
    src: "{{ custom_dockerfile | default('docker-compose.yml.j2') }}"
    dest: "{{ dockerfile_directory }}/{{ dockerfile_name }}"
    mode: 0644

- name: Run docker-docker
  include_tasks: "docker-compose-{{ ansible_distribution }}.yaml"
