---
- name: Create folder for docker-compose
  file:
    path: "{{ dockerfile_directory }}"
    state: directory
    mode: '0755'
- name: copy compose to the machine
  template:
    src: ../files/docker-compose.yml.j2
    dest: "{{ dockerfile_directory }}/{{ dockerfile_name }}"
    mode: 0644
- name: Run docker-docker
  include: "docker-compose-{{ ansible_distribution }}.yaml"
