---

- set_fact:
    ec2_stop_time_sec: "{{ now(False, '%s') }}"

- name: stop ec2 host
  shell: aws ec2 stop-instances --instance-ids {{ instance_id }}
  delegate_to: 127.0.0.1
  retries: "{{ retries | int }}"
  delay: "{{ delay | int }}"
  register: result
  until: result.rc == 0

- name: wait until ec2 host is stopped
  shell: aws ec2 wait instance-stopped --instance-ids {{ instance_id }}
  delegate_to: 127.0.0.1


...