---

- name: stat on file
  stat:
    path: "{{ attributes.name }}"
  register: st

- name: fail if file does not exist
  fail:
    msg: "File does not exist"
  when: not st.stat.exists

- name: fail if permissions are incorrect
  fail:
    msg: "{{ file }} permissions {{ st.stat.mode }} should be {{ permissions }}"
  when: attributes.permissions  != st.stat.mode

...
