---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: centos-8
    image: centos:8
    dockerfile: Dockerfile.centos8
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment: { container: docker }
  - name: ubuntu-1804
    image: ubuntu:18.04
    privileged: true
    dockerfile: Dockerfile.ub1804
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
    environment: { container: docker }
provisioner:
  name: ansible
  lint: |
    ansible-lint
  inventory:
    host_vars:
      centos-8:
        ansible_python_interpreter: /usr/bin/python3
      ubuntu-1804:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
  lint: |
    ansible-lint
