---
- name: 'Download CrowdStrike Falcon DEB'
  get_url:
    url: "{{ api_base_url }}/sensors/entities/download-installer/v1?id={{ crowdstrike_falcon_hash }}"
    timeout: 120 
    headers:
      Authorization: "Bearer {{ crowdstrike_auth.json.access_token }}"
      Accept: "application/octet-stream"
      Content-Type: "application/json"
    dest: /tmp/falcon-sensor.deb
    mode: 0644

- name: 'Install the obtained DEB (apt)'
  apt:
    deb: /tmp/falcon-sensor.deb
    state: present
...