---
- name: 'Download CrowdStrike Falcon RPM'
  get_url:
    url: "{{ api_base_url }}/sensors/entities/download-installer/v1?id={{ crowdstrike_falcon_hash }}"
    timeout: 120
    headers:
      Authorization: "Bearer {{ crowdstrike_auth.json.access_token }}"
      Accept: "application/octet-stream"
      Content-Type: "application/json"
    dest: /tmp/falcon-sensor.rpm
    mode: 0644

- name: 'Install the obtained RPM (dnf)'
  dnf:
    name: /tmp/falcon-sensor.rpm
    state: present
    disable_gpg_check: true
...