---

- name: 'Auth to CrowdStrike API (Windows)'
  win_uri:
    url: "{{ api_base_url }}/oauth2/token"
    url_method: POST
    body: "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: yes
    status_code: 201
    headers:
      Accept: "application/json"
      Content-Type: "application/x-www-form-urlencoded"
  register: crowdstrike_auth
  when: ansible_facts['os_family'] == 'Windows'

- name: 'Download CrowdStrike Falcon EXE'
  win_get_url:
    url: "{{ api_base_url }}/sensors/entities/download-installer/v1?id={{ crowdstrike_falcon_hash }}"
    url_timeout: 120
    headers:
      Authorization: "Bearer {{ crowdstrike_auth.json.access_token }}"
      Accept: "application/octet-stream"
      Content-Type: "application/json"
    dest: "{{ win_download_path }}"

- name: 'Install the obtained EXE (windows)'
  win_package:
    path: "{{ win_download_path }}"
    state: present
    expected_return_code:
      # The program has been installed
      - 0
      # The program is already present
      - 1638
      # falcon-sensor itself prevents reinstalling
      - 106
    arguments:
      - /install
      - /quiet
      - /norestart
      - "CID={{ falcon_customer_id }}"
...