---
- name: Run docker compose
  shell: "/usr/local/lib/docker/cli-plugins/docker-compose -f /srv/newrelic-infra_{{ target_agent_version }}/docker-compose_{{ target_agent_version }}.yml down"
  when: ansible_distribution in ['Amazon','Debian','SLES','Ubuntu']

- name: Run docker compose
  shell: "docker compose -f /srv/newrelic-infra_{{ target_agent_version }}/docker-compose_{{ target_agent_version }}.yml down"
  when: ansible_distribution in ['CentOS','RedHat']

...
