---

- name: default to latest version
  set_fact:
    target_agent_version_or_latest: "latest"
  when: target_version | length == 0

- name: pìnned target version
  set_fact:
    target_agent_version_or_latest: "{{ target_version }}"
  when: target_version | length > 0

- name: Run docker compose
  shell: "/usr/local/lib/docker/cli-plugins/docker-compose -f /srv/newrelic-infra_{{ target_agent_version_or_latest }}/docker-compose_{{ target_agent_version_or_latest }}.yml down"
  when: ansible_distribution in ['Amazon','Debian','SLES','Ubuntu']

- name: Run docker compose
  shell: "docker compose -f /srv/newrelic-infra_{{ target_agent_version_or_latest }}/docker-compose_{{ target_agent_version_or_latest }}.yml down"
  when: ansible_distribution in ['CentOS','RedHat']

...
