---
- name: Install New Relic OpenTelemetry Collector Distribution in a host
  ansible.builtin.include_tasks: host-install.yaml
  when: not uninstall and not collector_is_containerized

- name: Install New Relic OpenTelemetry Collector Distribution in a container
  ansible.builtin.include_tasks: containerized-install.yaml
  when: not uninstall and collector_is_containerized

- name: Uninstall New Relic OpenTelemetry Collector Distribution in a host
  ansible.builtin.include_tasks: host-uninstall.yaml
  when: uninstall and not collector_is_containerized

- name: Uninstall New Relic OpenTelemetry Collector Distribution in a container
  ansible.builtin.include_tasks: containerized-uninstall.yaml
  when: uninstall and collector_is_containerized


...