---

- name: prepare permissions
  set_fact:
    processed_files: "{{ [] | union( [{'permissions': item.value, 'name': item.key}] ) }}"
  loop: "{{ files | dict2items }}"

- ansible.builtin.include_role:
    name: assert_files
  vars:
    files: "{{ processed_files }}"

...
