- name: Retrieve packages information from repository
  uri:
    url: "{{ release_url }}"
    return_content: true
  register: github_packages

# Setup/install tasks.
- include_tasks: host/setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- include_tasks: host/setup-Debian.yml
  when: ansible_os_family == 'Debian'


# Collector configuration.
- name: Copy custom configuration
  template:
    src: "{{ custom_config_file }}"
    dest: "{{ '/etc/' + distribution  + '/config.yml' }}"
    mode: 0644
  when: custom_config_file | length > 0
  notify:
    - restart collector

- name: Copy configuration template
  template:
    src: "{{ collector_config_tpl }}"
    dest: "{{ '/etc/' + distribution  + '/config.yaml' }}"
    mode: 0644
  when: custom_config_file == ""
  notify:
    - restart collector
