---
- name: Install Open Telmetry Collector in a host
  ansible.builtin.include_tasks: host-installation.yml
  when: collector_is_containerized == false

- name: Install Open Telmetry Collector in a container
  ansible.builtin.include_tasks: install-containerized.yml
  when: collector_is_containerized == true
