---

- name: download msi package
  win_get_url:
    url: "{{ package }}"
    dest: "C:\\{{ package | basename}}"
    force: yes

- name: install msi package
  win_package:
    path: "C:\\{{ package | basename}}"
    state: present

- name: set service startup mode to auto and ensure it is started
  win_service:
    name: "{{ service_windows }}"
    start_mode: auto
    state: started
  when: service_windows | length > 0

...