---

- name: Add version when present
  set_fact:
    versioned_package: "{{ package }}-{{ target_version }}"
    state: "present"
  when: target_version | length > 0

- name: Install package yum
  environment: "{{ env_vars }}"
  yum:
    name: "{{ versioned_package }}"
    update_cache: yes
    state: "{{ state }}"
    update_only: "{{ install_only_if_present }}" #for some reason w/o this package is not being updated in al2
  retries: 5
  delay: 60
  when: not "python3" in ansible_python_interpreter

- name: Install package dnf
  environment: "{{ env_vars }}"
  dnf:
    name: "{{ versioned_package }}"
    update_cache: yes
    state: "{{ state }}"
    update_only: "{{ install_only_if_present }}" #for some reason w/o this package is not being updated in al2
  retries: 5
  delay: 60
  when: "'python3' in ansible_python_interpreter"

...
