---

- name: Add version when present
  set_fact:
    versioned_package: "{{ package }}-{{ target_version }}"
  when: target_version | length > 0

- name: zypper install package
  environment: "{{ env_vars }}"
  zypper:
    name: "{{ versioned_package }}"
    state: present
    oldpackage: yes
    update_cache: yes
    force: yes
  retries: 5
  delay: 60

...
