---

- name: Install package yum
  environment: "{{ env_vars }}"
  yum:
    name: "{{ versioned_package }}"
    update_cache: yes
  retries: 5
  delay: 60
  when: not "python3" in ansible_python_interpreter

- name: Install package dnf
  environment: "{{ env_vars }}"
  dnf:
    name: "{{ versioned_package }}"
    update_cache: yes
  retries: 5
  delay: 60
  when: "'python3' in ansible_python_interpreter"

...
