---

- name: zypper install package
  environment: "{{ env_vars }}"
  zypper:
    name: "{{ package }}"
    state: present
    oldpackage: yes
    update_cache: yes
    force: yes
  retries: 5
  delay: 60

...
