- name: register brew path
  ansible.builtin.set_fact:
    brew_path: /opt/homebrew
    when: ansible_architecture == "arm64"

- name: register brew path
  ansible.builtin.set_fact:
    brew_path: /usr/local
  when: ansible_architecture == "x86_64"

- name: install package
  command: "{{ brew_path }}/bin/brew install {{ package }}"

