---

- name: fail if username is not defined
  fail:
    msg: username variable must be specified
  when: (username is not defined) or (username | length == 0)


- ansible.builtin.include_tasks: "check-{{ ansible_system }}.yaml"

...
