---

- name: prepare files
  set_fact:
    processed_files: "{{ processed_files|default([]) | union( [{'owner': username, 'name': item}] ) }}"
  loop: "{{ user_files }}"

- name: prepare processes
  set_fact:
    processed_processes: "{{ processed_processes|default([]) | union( [{'owner': username, 'name': item}] ) }}"
  loop: "{{ user_processes }}"

- ansible.builtin.include_role:
    name: assert_files
  vars:
    files: "{{ processed_files }}"
    processes: "{{ processed_processes }}"

...
