---

- name: install docker
  ansible.builtin.include_tasks: "install-docker-{{ ansible_distribution }}.yaml"

- name: ensure docker service is started
  ansible.builtin.service:
    name: docker
    state: started
...
