---

- name: install New Relic Infra Repo APT key
  apt_key:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg

- name: remove New Relic Infra APT repository (from previous runs)
  apt_repository:
    filename: "{{ repo_name }}"
    repo: "deb {{ item }}/linux/apt {{ ansible_distribution_release }} main"
    state: absent
    update_cache: no #ubuntu 20.10 image has broken repos. Cache will only be updated after NR repo is added
  loop: "{{ repos_to_clean }}"

- name: install New Relic Infra APT repository
  apt_repository:
    repo: "deb {{ repo_endpoint }}/linux/apt {{ ansible_distribution_release }} main"
    filename: "{{ repo_name }}"
    update_cache: no

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  ignore_errors: true #ubuntu 20.10 image has broken repos so ignore errors

...
