---

- name: remove New Relic Infra Zypper repository (from previous runs)
  zypper_repository:
    name: "{{ repo_name }}"
    state: absent

- name: install New Relic Infra Zypper repository
  zypper_repository:
    name: "{{ repo_name }}"
    description: New Relic Infrastructure Agent
    repo: "{{ repo_endpoint }}/linux/zypp/sles/{{ansible_distribution_version}}/{{ansible_machine}}/"
    runrefresh: yes
    auto_import_keys: yes
    disable_gpg_check: yes
    state: present
  register: infra_agent_zypper_repo

...
