---

- name: remove New Relic Infra YUM repository (from previous runs)
  yum_repository:
    name: newrelic-infra
    state: absent

- name: install New Relic Infra YUM repository
  yum_repository:
    name: "{{ repo_name }}"
    description: New Relic Infrastructure
    baseurl: "{{ repo_endpoint }}/linux/yum/el/$releasever/$basearch"
    gpgkey: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    gpgcheck: no
    repo_gpgcheck: no

- name: clean yum cache
  # https://github.com/ansible/ansible/pull/31450#issuecomment-352889579
  command:
    cmd: yum clean all

...
